- precision_immuno.py
resolves #11
All indexes for the run are downloaded in separate jobs allowing for parallel downloads and reducing the time taken on the ramping stage.
> Implement reference download in parallel jobs (resolves #11)

- ProTECT.py
> Fix sample download for S3 urls (resolves #36)

- MANUAL.md
- README.md
- required_docker_tools.txt
> Update README (resolves #40)

- MANUAL.md
- input_parameters.yaml
resolves #42
resolves #44
resolves #47
Thanks to @Jeltje for all the critique and comments.
> Update README and MANUAL (resolves #42, resolves #44, resolves #47)

- MANUAL.md
- src/protect/pipeline/ProTECT.py
> Implement generate_config CL flag (resolves #51)

- src/protect/pipeline/ProTECT.py
- src/protect/pipeline/input_parameters.yaml
> Fix star and gencode peptide files links in config (revolves #60)

- jenkins.sh
> Install Toil and s3am in jenkins.sh (resolves #57)

- MANUAL.md
- src/protect/pipeline/ProTECT.py
resolves #59
resolves #62
Added info about workdirs and space constraints
Added info about absolute paths
> Update manual (resolves #59, resolves #62)

- src/protect/pipeline/input_parameters.yaml
> Add dbsnp_tbi to input_parameter.yaml (resolves #65)

- src/protect/pipeline/ProTECT.py
resolves #28
Added a command line flag for max cpus to use per job
Th number of cpus is now at least 6 and at most max_cpus.
> Modify how cpus are allocated to large jobs (resolves #28)

- .gitignore
- jenkins.sh
- setup.py
- src/protect/alignment/common.py
- src/protect/alignment/dna.py
- src/protect/alignment/rna.py
- src/protect/binding_prediction/common.py
- src/protect/binding_prediction/mhcii.py
- src/protect/expression_profiling/rsem.py
- src/protect/haplotyping/phlat.py
- src/protect/mutation_annotation/snpeff.py
- src/protect/mutation_calling/muse.py
- src/protect/mutation_calling/mutect.py
- src/protect/mutation_calling/radia.py
- src/protect/pipeline/ProTECT.py
- src/protect/qc/rna.py
- src/protect/test/__init__.py
- src/protect/test/unit/test_alignments.py
- src/protect/version.py
- version.py
resolves #4
Each job now requests for disk based on the size of its input files.
ProTECT now requires Toil==3.3.0
> Dynamically request disk for jobs (resolves #4)

- Makefile
- src/protect/expression_profiling/rsem.py
- src/protect/haplotyping/phlat.py
- src/protect/mutation_calling/common.py
- src/protect/mutation_calling/muse.py
- src/protect/mutation_calling/mutect.py
- src/protect/mutation_calling/somaticsniper.py
- src/protect/pipeline/ProTECT.py
- src/protect/test/unit/test_mutation_callers.py
> Implement Somatic Sniper support (resolves #33)

- MANIFEST.in
- setup.py
> Add input_parameters.yaml to the Pypi dist (resolves #78)

- MANUAL.md
- README.md
- src/protect/mutation_calling/common.py
- src/protect/mutation_calling/somaticsniper.py
- src/protect/mutation_calling/strelka.py
- src/protect/pipeline/ProTECT.py
- src/protect/pipeline/input_parameters.yaml
- src/protect/test/__init__.py
- src/protect/test/test_inputs/ci_parameters.yaml
- src/protect/test/unit/test_mutation_callers.py
> Implement Strelka support (resolves #73)

- MANUAL.md
> Update s3am description in the manual (resolves #83)

- src/protect/common.py
- src/protect/mutation_calling/common.py
> Fix overwrite to s3 in export_results (resolves #85)

- src/protect/common.py
> Export on a per-sample basis (resolves #90)

- src/protect/pipeline/ProTECT.py
- src/protect/version.py
> Remove max-cores-per-job from mutual group (resolves #95)

- src/protect/alignment/rna.py
- src/protect/pipeline/ProTECT.py
> Reduce star memory footprint (resolves #97)

- src/protect/pipeline/ProTECT.py
> Fix max-cores (resolves #101)

- src/protect/mutation_translation.py
- src/protect/pipeline/ProTECT.py
- src/protect/test/test_inputs/ci_parameters.yaml
> Add support for new RNA-aware transgene (resolves #107)

- required_docker_tools.txt
- src/protect/mutation_translation.py
> Use legacy Transgene for older releases

- src/protect/addons.py
- src/protect/alignment/common.py
- src/protect/binding_prediction/common.py
- src/protect/common.py
- src/protect/expression_profiling/rsem.py
- src/protect/haplotyping/phlat.py
- src/protect/mutation_annotation/snpeff.py
- src/protect/mutation_calling/common.py
- src/protect/mutation_calling/muse.py
- src/protect/mutation_calling/mutect.py
- src/protect/mutation_calling/radia.py
- src/protect/mutation_translation.py
- src/protect/pipeline/ProTECT.py
- src/protect/rankboost.py
> Use filestore exportFile instead of s3am (resolves #126)

- Makefile
- jenkins.sh
- setup.py
- src/protect/alignment/rna.py
resolves #129
~~Bumping to 3.5.0a1.dev290 so we do not encounter the restart bug~~
Update: Bumping to release 3.5.0
> Bump Toil requirement to higher version (resolves #129)

- Flowchart.txt
- MANUAL.md
- required_docker_tools.txt
Resolves #134 
Update out-of-date information in the documentation.
> Update documentation (Resolves #134)

- src/protect/alignment/dna.py
- src/protect/alignment/rna.py
- src/protect/common.py
Star was using float memory
bwa wasn't even using cores
export to s3 was problematic due to boto outages
> Fix bugs seen in 10-sample TARGET run

- required_docker_tools.txt
- src/protect/alignment/common.py
- src/protect/alignment/dna.py
- src/protect/alignment/rna.py
- src/protect/binding_prediction/mhci.py
- src/protect/binding_prediction/mhcii.py
- src/protect/common.py
- src/protect/expression_profiling/rsem.py
- src/protect/haplotyping/phlat.py
- src/protect/mutation_annotation/snpeff.py
- src/protect/mutation_calling/muse.py
- src/protect/mutation_calling/radia.py
- src/protect/mutation_calling/somaticsniper.py
- src/protect/mutation_calling/strelka.py
- src/protect/mutation_translation.py
- src/protect/qc/rna.py
- src/protect/rankboost.py
Related to #138
Future versions will support user-specified tool version choices.
> Hardcode tool docker versions (related to #138)

- src/protect/expression_profiling/rsem.py
- src/protect/pipeline/ProTECT.py
> Fix rsem call in ProTECT (Resolves #144)

- src/protect/expression_profiling/rsem.py
- src/protect/pipeline/ProTECT.py
> Fix rsem wrapper (Resolves #144)

- required_docker_tools.txt
- src/protect/mutation_translation.py
> Bump Transgene version to 2.0.0 (resolves #158)

- docker/pipelineWrapper.py
- docker/protect.cwl
Changes the output structure as discussed and updates the CWL output bindings correspondingly.
> Improve Docker output structure

- Flowchart.txt
- MANUAL.md
- Makefile
- jenkins.sh
- required_docker_tools.txt
- setup.py
- src/protect/binding_prediction/common.py
- src/protect/binding_prediction/mhci.py
- src/protect/binding_prediction/mhcii.py
- src/protect/common.py
- src/protect/mutation_translation.py
- src/protect/pipeline/ProTECT.py
- src/protect/pipeline/defaults.yaml
- src/protect/pipeline/input_parameters.yaml
- src/protect/pipeline/required_entries.yaml
- src/protect/rankboost.py
- src/protect/test/ci/test_protect.py
- src/protect/test/test_inputs/ci_parameters.yaml
- src/protect/test/unit/test_rankboost.py
- src/protect/test/unit/test_spawn_antigen_predictors.py
> Implement alt-self support (resolves #123)

- MANUAL.md
- required_docker_tools.txt
- src/protect/alignment/dna.py
- src/protect/expression_profiling/rsem.py
- src/protect/mutation_annotation/snpeff.py
- src/protect/mutation_calling/radia.py
- src/protect/pipeline/ProTECT.py
- src/protect/pipeline/defaults.yaml
- src/protect/pipeline/input_parameters.yaml
- src/protect/pipeline/required_entries.yaml
- src/protect/test/__init__.py
- src/protect/test/test_inputs/ci_parameters.yaml
- src/protect/test/unit/test_snpeff.py
- src/protect/test/unit/test_transgene
> Add hg38 support (resolves #161)

- required_docker_tools.txt
- src/protect/pipeline/defaults.yaml
- src/protect/pipeline/input_parameters.yaml
> Bump rank boost to 2.0.3 (resolves #174)

- MANUAL.md
- src/protect/common.py
- src/protect/mutation_translation.py
- src/protect/pipeline/ProTECT.py
resolves #176 
resolves #178
resolves #179
> Fix multiple issues (resolves #176, resolves #178, resolves #179)

- MANUAL.md
- Makefile
- src/protect/addons.py
- src/protect/alignment/common.py
- src/protect/common.py
- src/protect/pipeline/ProTECT.py
- src/protect/pipeline/required_entries.yaml
- src/protect/test/__init__.py
- src/protect/test/ci/test_protect.py
- src/protect/test/test_inputs/ci_all_fastq_parameters.yaml
- src/protect/test/test_inputs/ci_mix_bam_fastq_parameters.yaml
- src/protect/test/test_inputs/ci_vcf_fastq_parameters.yaml
- src/protect/test/unit/test_file_downloads.py
- src/protect/test/unit/test_mhc_pathway_assessment.py
- src/protect/test/unit/test_mutation_callers.py
- src/protect/test/unit/test_rankboost.py
- src/protect/test/unit/test_snpeff.py
- src/protect/test/unit/test_spawn_antigen_predictors.py
- src/protect/test/unit/test_transgene
> Support startup from checkpoints (resolves #168)

- MANUAL.md
- src/protect/mutation_translation.py
- src/protect/pipeline/ProTECT.py
- src/protect/pipeline/defaults.yaml
- src/protect/pipeline/input_parameters.yaml
- src/protect/test/test_inputs/ci_all_fastq_parameters.yaml
> Implement optional OxoG filtering (resolves #184)

- src/protect/binding_prediction/common.py
resolves #186
Correct index was 4, not 5 for pept
> Fix index in _process_sturniolo_mhcii (resolves #186)

- MANUAL.md
- src/protect/alignment/rna.py
- src/protect/binding_prediction/common.py
- src/protect/common.py
- src/protect/mutation_calling/common.py
- src/protect/mutation_calling/fusion.py
- src/protect/mutation_translation.py
- src/protect/pipeline/ProTECT.py
- src/protect/pipeline/defaults.yaml
- src/protect/pipeline/input_parameters.yaml
- src/protect/test/ci/test_protect.py
- src/protect/test/test_inputs/ci_all_fastq_parameters.yaml
- src/protect/test/test_inputs/ci_mix_bam_fastq_parameters.yaml
- src/protect/test/test_inputs/ci_parameters.yaml
- src/protect/test/test_inputs/ci_vcf_fastq_parameters.yaml
- src/protect/test/unit/test_alignments.py
- src/protect/test/unit/test_mutation_callers.py
> Add fusion support (resolves #1)

- src/protect/alignment/common.py
- src/protect/alignment/dna.py
- src/protect/mutation_calling/muse.py
- src/protect/mutation_calling/radia.py
- src/protect/mutation_calling/somaticsniper.py
- src/protect/mutation_calling/strelka.py
- src/protect/qc/rna.py
> Reevaluate underestimated disk requirements. (Resolves #127)

- MANUAL.md
- jenkins.sh
- setup.py
- src/protect/alignment/dna.py
- src/protect/common.py
- src/protect/mutation_calling/common.py
- src/protect/mutation_calling/muse.py
- src/protect/mutation_calling/mutect.py
- src/protect/mutation_calling/radia.py
- src/protect/mutation_calling/somaticsniper.py
- src/protect/mutation_calling/strelka.py
- src/protect/pipeline/ProTECT.py
- src/protect/pipeline/defaults.yaml
- src/protect/pipeline/input_parameters.yaml
> Implement gdc download support (resolves #188)

- MANUAL.md
- src/protect/common.py
- src/protect/pipeline/ProTECT.py
- src/protect/pipeline/input_parameters.yaml
- src/protect/test/test_inputs/ci_all_fastq_parameters.yaml
> Add email updates (Resolves #121)

- src/protect/mutation_calling/fusion.py
> Fix fusion race caused by lack of encapsulation (resolves #193)

- src/protect/pipeline/defaults.yaml
- src/protect/test/test_inputs/ci_all_fastq_parameters.yaml
> Add mail_to to defaults (Resolves #198)

- src/protect/pipeline/ProTECT.py
resolves #197
Also moved fusion code up to handle incorrectly made subgraph.
> Disallow fusion detection without input Tumor RNA fastq (resolves #197)

- setup.py
> Bump toil to 3.8.0 (resolves #202)

- src/protect/test/unit/test_mutation_callers.py
> Fix broken fusion test (resolves #204)

- docker/Makefile
- docker/Makefile.template
- docker/protect.cwl
> Fix CWL descriptor and dockstore support (resolves #207)

- docker/Makefile
- docker/Makefile.template
- docker/protect.cwl
> Fix cwl descriptor (resolves #207)

- docker/Dockerfile.template
- jenkins.sh
- setup.py
resolves #210
Fixed jenkins to show 1.2.0 (This should fail)
> Add code to ensure gdc-client v1.2.0 is blacklisted (resolves #210)

- docker/Dockerfile.template
- jenkins.sh
- setup.py
> Blacklist gdc 1.2.0 (resolves #210)

- docker/protect.cwl
- docker/protect.json
Add missing -prefix and fix formatting
fixed up comments for foaf and usage
anonymous email fix
> Add cwl fixes (resolves #218)

- src/protect/alignment/dna.py
> Add mark duplicates to DNA processing (resolves #229)

- required_docker_tools.txt
- src/protect/binding_prediction/common.py
- src/protect/binding_prediction/mhcii.py
- src/protect/mutation_translation.py
- src/protect/pipeline/defaults.yaml
> Gracefully handle no actionable mutations (resolves  #232)

- required_docker_tools.txt
- src/protect/alignment/dna.py
- src/protect/binding_prediction/common.py
- src/protect/binding_prediction/mhcii.py
- src/protect/mutation_translation.py
- src/protect/pipeline/defaults.yaml
> Cherry pick from master (#232, #234)

- src/protect/common.py
- src/protect/pipeline/ProTECT.py
- src/protect/test/test_inputs/ci_vcf_bedpe_haplotype_expression_parameters.yaml
> Allow startup with expression and fusion bedpe (resolves #242)

- required_docker_tools.txt
- src/protect/binding_prediction/common.py
- src/protect/mutation_calling/common.py
- src/protect/mutation_calling/fusion.py
- src/protect/pipeline/defaults.yaml
- src/protect/pipeline/input_parameters.yaml
- src/protect/test/test_inputs/ci_vcf_bedpe_haplotype_expression_parameters.yaml
> Implement indel support (resolves#2)

- jenkins.sh
- setup.py
> Fix toil in setup.py (resolves #250)

- src/protect/common.py
> Fix annotations.txt in gdc download (resolves #215)

- attic/precision_immuno.py
- src/protect/addons/assess_car_t_validity.py
- src/protect/addons/assess_immunotherapy_resistance.py
- src/protect/addons/assess_mhc_pathway.py
- src/protect/alignment/common.py
- src/protect/alignment/dna.py
- src/protect/alignment/rna.py
- src/protect/binding_prediction/common.py
- src/protect/binding_prediction/mhci.py
- src/protect/binding_prediction/mhcii.py
- src/protect/expression_profiling/rsem.py
- src/protect/haplotyping/phlat.py
- src/protect/mutation_annotation/snpeff.py
- src/protect/mutation_calling/common.py
- src/protect/mutation_calling/fusion.py
- src/protect/mutation_calling/indel.py
- src/protect/mutation_calling/muse.py
- src/protect/mutation_calling/mutect.py
- src/protect/mutation_calling/radia.py
- src/protect/mutation_calling/somaticsniper.py
- src/protect/mutation_calling/strelka.py
- src/protect/mutation_translation.py
- src/protect/qc/rna.py
- src/protect/rankboost.py
resolves #254 
Changed logging messages to execute just before functions return to signify completion of events that have been executed.
> change the logging messages so that they occur after events (resolves #254)

- MANUAL.md
- Makefile
- jenkins.sh
- setup.py
> Fix the setuptools code so that the correct names are used (resolves #266)

- MANUAL.md
resolves #274
Added a troubleshooting section to MANUAL.md that
talks about the packaging issue during installation
and the non-deterministic RADIA failures.
> Add troubleshooting to MANUAL.md (resolves #274)

- src/protect/alignment/dna.py
> Add memory requirement to DNA alignment (resolves #278)

- src/protect/mutation_translation.py
- src/protect/test/ci/test_protect.py
resolves #281
The fusion bedpe emited by Transgene is now exported to
`mutations/transgened`
> Export transgene fusions (resolves #281)

- src/protect/binding_prediction/common.py
resolves #284
We now print a message and return 'N' * peplen
> Fix event with inconsistency in normals with many IARS(resolves #284)
